#!/usr/bin/env ruby

require 'open3'
require 'optparse'

class TarMuxCLI

  def initialize
    # Default option values
    @options = {source_folder: "."}
  end

  def create_parser
    OptionParser.new do |opts|
      opts.banner = get_optparse_banner

      opts.on('-d', '--destination-folder DEST', 'The directory where the tarballs will be saved')
      opts.on('-s', '--source-folder [SOURCE]', 'The directory containing the subdirectories to be tarballed')
    end
  end

  def parse!(args)
    option_parser = create_parser

    begin
      option_parser.parse!(args, into: @options)
    rescue OptionParser::InvalidOption => opt_err
      puts "#{opt_err.message}\n".red
      puts option_parser.help
      exit 1
    end

    @options
  end

  def get_optparse_banner()
  "
Create individual tarballs for each subdirectory in a directory.

Usage: #{File.basename($PROGRAME_NAME)} [options]
"
  end
end

class TarMux

  def initialize(destination_folder:, source_folder:)
    @dest_folder = destination_folder
    @source_folder = source_folder
  end

  def run()
    # match hidden dot folders by default
    glob_opts = File::FNM_DOTMATCH

    Dir.chdir(@source_folder) do
      children = Dir.glob('*', glob_opts)
      target_folders = children.select { |d| File.directory? d }
      #tar_folders(target_folders)
      tar_folders(target_folders) { |cmd| puts "#{cmd}" }
    end
  end

  def tar_folders(folders)
    folders.each do |f|
      tar_cmd = %(tar -I 'gzip -9' cvf "#{@dest_folder}/#{f}.tgz" "#{f}")

      if block_given?
        yield(tar_cmd)
      else
        run_command(tar_cmd)
      end
    end
  end

  def run_command(shell_cmd)
    Open3.popen3("bash") do | stdin, stdout, stderr, wait_thread |

      stdout_thr = Thread.new { stdout.each {|line| puts line } }
      stderr_thr = Thread.new { stderr.each {|line| puts line.red } }

      stdin.puts(shell_cmd)

      wait_thread.value
    end
  end
end

# Make the ASCII run red with the blood of the STDERR's enemies
class String
  def red
    "\e[31m#{self}\e[0m"
  end
end

puts "script name: #{File.basename(__FILE__)}"

#options = TarMuxCLI.new.parse!(ARGV)
#TarMux.new(**options).run

#tarmux --destination_folder "/cygdrive/d/src/Tardis/old-work-src"
